version: "3.3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      - frontend
    depends_on:
      - redis
        
  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend
        
  db:
    image: postgres:13.1-alpine
    volumes:
      - db-data:/data/dbdata
    networks:
      - backend
      
networks:
   frontend:
   backend:
   
volumes:
  db-data:
